#:schema https://jj-vcs.github.io/jj/latest/config-schema.json

[user]
email = "modest@meowth.dev"
name = "Modest Meowth"

[git]
auto-local-branch = true

[aliases]
tug = ["bookmark", "move", "--from", "heads(::@- & bookmarks())", "--to", "@-"]
rebase-all = ["rebase", "-s", "all:roots(trunk()..mutable())", "-d", "trunk()"]

[revset-aliases]
"p(n)" = "p(@, n)"
"p(r, n)" = "roots(r | ancestor(r-, n))"

[snapshot]
max-new-file-size = 4194304

[ui]
default-command = ["log", "--reversed"]

[templates]
log_node = '''
if(self && !current_working_copy && !immutable && !conflict && in_branch(self),
  "◇",
  builtin_log_node
)
'''

[template-aliases]
"in_branch(commit)" = 'commit.contained_in("immutable_heads()..bookmarks()")'
