keys:
  - &roci_host_age age1xltxc87jgp6fzjlwapfctpa23vaqn2cqwqyta8vh0g0yrgs6adfqs0arc9
  - &vdrm_host_age age1f5hmq63suekp3tcy8886x406nw79z8hc3l6sj3kk4s3reuhg8d0s2jf4tu
  - &roci_mm_age age18lt2qwmtvuj0ujf9zrxr4wsehhxuvqc3e79s53c20wq5fv6jhqyst4m83t
  - &vdrm_mm_age age1vz6akhdt4hwfxe3d2n7er2nym7lttcg7uchafysajdtwa696zcyq6latjk
  - &pnby_mm_age age1tx6m00qdxu0kfgxwkw8nhltd3kr0jgysmm2eje67tdvhlq8fuc5sxgww8a
creation_rules:
  - path_regex: .*\.sops.ya?ml$
    key_groups:
      - pgp: []
        age:
          - *roci_host_age
          - *vdrm_host_age
          - *roci_mm_age
          - *vdrm_mm_age
          - *pnby_mm_age
