keys:
  - &pnby_age age15fhvwthgd5f6spcvr5st3lknm3xqlfdyj2s3xnld8c947w78s9nsl0q8zv
  - &roci_age age1xltxc87jgp6fzjlwapfctpa23vaqn2cqwqyta8vh0g0yrgs6adfqs0arc9
  - &vdrm_age age1f5hmq63suekp3tcy8886x406nw79z8hc3l6sj3kk4s3reuhg8d0s2jf4tu
  - &skmn_age age1qzdr0e56jx3gvq8cqexp344sed4pjcyjg6vpwwfvhjcyu37v8f5s4dg4a8
  - &thtp_age age12hqwenhrfsxsttejyhjf2z894mv5tynt4yyjann0z09mdew45qqswhe4p0
  - &mm_age age18lt2qwmtvuj0ujf9zrxr4wsehhxuvqc3e79s53c20wq5fv6jhqyst4m83t
creation_rules:
  - path_regex: .*\.sops.ya?ml$
    key_groups:
      - age:
          - *pnby_age
          - *roci_age
          - *vdrm_age
          - *skmn_age
          - *thtp_age
          - *mm_age
