# https://numtide.github.io/devshell
motd = "Just $(just --list)"

[[env]]
name = "DIRENV_WARN_TIMEOUT"
value = 0

[[commands]]
package = "unstable.just"

[devshell]
packages = [
  "pkgs.nvfetcher",
  "pkgs.treefmt",
  "pkgs.nixpkgs-fmt",
  "pkgs.taplo",
  "pkgs.yamlfmt",
  "pkgs.pre-commit",
  "pkgs.pre-commit-hook-ensure-sops",
]
