# https://numtide.github.io/devshell

[[env]]
name = "DIRENV_WARN_TIMEOUT"
value = 0

[[commands]]
package = "unstable.just"

[devshell]
packages = [
  "pkgs.nvfetcher",
  "unstable.treefmt",
  "pkgs.nixpkgs-fmt",
  "pkgs.taplo",
  "pkgs.yamlfmt",
  "pkgs.pre-commit",
  "pkgs.pre-commit-hook-ensure-sops",
]
