"$schema" = "https://starship.rs/config-schema.json"
palette = "dracula"

format = """
$username\
$os\
$hostname\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$golang\
$rust\
$nodejs\
$nix_shell\
$battery\
$time\
$status\
$line_break\
$container\
$shell\
$character"""

[character]
error_symbol = "[Œª](bold red)"
success_symbol = "[Œª](bold green)"

[cmd_duration]
style = "bold yellow"

[directory]
style = "bold green"
format = "[ $path ]($style)"

[directory.substitutions]
"Documents" = "Û∞àô "
"Downloads" = "ÔÄô "
"Music" = "ÔÄÅ "
"Pictures" = "ÔÄæ "

[git_branch]
symbol = "Ôêò"
style = "bold pink"
format = "[$symbol $branch ]($style)"

[git_status]
style = "bold red"
format = "[($all_status$ahead_behind) ]($style)"

[hostname]
style = "bold purple"
ssh_only = true

[os]
disabled = false

[shell]
disabled = false
bash_indicator = "[\\$ ](bold red)"
fish_indicator = "[Û∞à∫ ](bold orange)"
powershell_indicator = "[>_ ](bold yellow)"
unknown_indicator = "? "

[time]
style = "bold orange"
disabled = false
time_format = "%R"
format = "[ Ôê∫ $time ]($style)"

[username]
show_always = true
style_user = "bold cyan"

[golang]
symbol = "üêπ"
format = "[$symbol$version ]($style)"

[nix_shell]
symbol = "‚ùÑÔ∏è"
format = "[$symbol$name]($style)"

[palettes.dracula]
background = "#282a36"
current_line = "#44475a"
foreground = "#f8f8f2"
comment = "#6272a4"
cyan = "#8be9fd"
green = "#50fa7b"
orange = "#ffb86c"
pink = "#ff79c6"
purple = "#bd93f9"
red = "#ff5555"
yellow = "#f1fa8c"
