keys:
  - &thtp_age age12hqwenhrfsxsttejyhjf2z894mv5tynt4yyjann0z09mdew45qqswhe4p0
  - &mm_age age18lt2qwmtvuj0ujf9zrxr4wsehhxuvqc3e79s53c20wq5fv6jhqyst4m83t
creation_rules:
  - path_regex: .*\.sops.ya?ml$
    key_groups:
      - age:
          - *thtp_age
          - *mm_age
