keys:
  - &skmn_host_age age1qzdr0e56jx3gvq8cqexp344sed4pjcyjg6vpwwfvhjcyu37v8f5s4dg4a8
  - &skmn_mm_age age1cdyvnexeckc9xt372avmh0cnjxxm5ydf0k0emk4yfx6ml5f6vplqv06uqu
creation_rules:
  - path_regex: .*\.sops.ya?ml$
    key_groups:
      - pgp: []
        age:
          - *skmn_host_age
          - *skmn_mm_age

