keys:
  - &skmn_host_age age1t4dvuc673na2l5v8vgdc038rf3m0g356rtujs7eje48ynug7vdjqdkjqr6
  - &skmn_mm_age age1cdyvnexeckc9xt372avmh0cnjxxm5ydf0k0emk4yfx6ml5f6vplqv06uqu
creation_rules:
  - path_regex: .*\.sops.ya?ml$
    key_groups:
      - pgp: []
        age:
          - *skmn_host_age
          - *skmn_mm_age

