# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  abbreviation-tips = {
    pname = "abbreviation-tips";
    version = "v0.7.0";
    src = fetchFromGitHub {
      owner = "gazorby";
      repo = "fish-abbreviation-tips";
      rev = "v0.7.0";
      fetchSubmodules = false;
      sha256 = "sha256-F1t81VliD+v6WEWqj1c1ehFBXzqLyumx5vV46s/FZRU=";
    };
  };
  keys = {
    pname = "keys";
    version = "latest";
    src = fetchurl {
      url = "https://github.com/ModestMeowth.keys";
      sha256 = "sha256-2y3t5kiYqO09UitlBxXCnqcyo5fHONdTUakzLw9o840=";
    };
  };
  yaml-companion-nvim = {
    pname = "yaml-companion-nvim";
    version = "0.1.3";
    src = fetchFromGitHub {
      owner = "someone-stole-my-name";
      repo = "yaml-companion.nvim";
      rev = "0.1.3";
      fetchSubmodules = false;
      sha256 = "sha256-9c+9oxrCNFMlAsRaamsimYbrYYXHpR4APljYMsjlrzY=";
    };
  };
}
